-- ignore “user already exists” (ORA‑01920)
BEGIN
  EXECUTE IMMEDIATE q'[
    CREATE USER todo_user IDENTIFIED BY todo_pass
      DEFAULT TABLESPACE USERS
      TEMPORARY TABLESPACE TEMP
  ]';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -1920 THEN -- not “user exists”
      RAISE;
    END IF;
END;
/

-- grant privileges (will succeed even if user pre‑exists)
BEGIN
  EXECUTE IMMEDIATE 'GRANT CREATE SESSION, CREATE TABLE TO todo_user';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

-- ignore “table already exists” (ORA‑00955)
BEGIN
  EXECUTE IMMEDIATE q'[
    CREATE TABLE todo_user.todo_do (
      id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      task_name VARCHAR2(255) NOT NULL,
      created_at TIMESTAMP DEFAULT SYSTIMESTAMP,
      is_done CHAR(1) DEFAULT ''N'' CHECK (is_done IN (''Y'',''N''))
    )
  ]';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -955 THEN -- not “name is already used”
      RAISE;
    END IF;
END;
/
